import streamlit as st
import time
from googleapiclient.discovery import build

# --- CONFIGURATION ---
# Replace these with your actual API Key and Custom Search Engine ID
YOUR_API_KEY = "REPLACE_WITH_YOUR_GOOGLE_API_KEY"
YOUR_CSE_ID = "REPLACE_WITH_YOUR_CSE_ID"

# --- PAGE SETUP ---
st.set_page_config(page_title="Multi-Agent Research System", layout="wide")

# --- HELPER FUNCTIONS ---

def render_graph(active_node):
    """
    Generates the Mermaid.js graph definition with the active node highlighted.
    """
    # Define styles
    style_def = """
    classDef default fill:#f9f9f9,stroke:#333,stroke-width:2px;
    classDef active fill:#ff9900,stroke:#333,stroke-width:4px,color:white;
    classDef success fill:#4BB543,stroke:#333,color:white;
    """
    
    # Define nodes and edges
    graph_def = """
    graph LR
        User((User Input)) --> Router{{"Router"}}
        Router --> |Needs Info| Searcher[("🔍 Search Agent")]
        Searcher --> |Raw Data| Analyst[("🧠 Analyst Agent")]
        Analyst --> Writer[("✍️ Writer Agent")]
        Writer --> Final((Final Output))
    """
    
    # Apply active class
    class_assign = f"class {active_node} active;"
    
    return f"{style_def}\n{graph_def}\n{class_assign}"

def run_google_search(query):
    """
    Executes a Google Custom Search using the provided API key and CSE ID.
    """
    try:
        service = build("customsearch", "v1", developerKey=YOUR_API_KEY)
        res = service.cse().list(q=query, cx=YOUR_CSE_ID).execute()
        return res.get('items', [])
    except Exception as e:
        # Re-raise the exception to be caught by the caller
        raise e

def run_analyst_agent(search_results):
    """
    Simulates an Analyst Agent processing the raw search data.
    """
    time.sleep(2) # Simulate processing time
    
    num_results = len(search_results)
    titles = [item.get('title', 'No Title') for item in search_results[:3]]
    
    analysis = f"""
    **Analysis Report:**
    - **Data Source:** Processed {num_results} raw search results.
    - **Key Themes:** Identified recurring topics in top articles.
    - **Top Sources:** {', '.join(titles)}
    - **Sentiment:** Neutral to Positive based on initial scan.
    """
    return analysis

def run_writer_agent(analysis_data, query):
    """
    Simulates a Writer Agent creating a final report.
    """
    time.sleep(2) # Simulate drafting time
    
    report = f"""
    ## 📑 Research Report: {query}
    
    ### Executive Summary
    Based on the analysis of recent data, we have compiled the following insights regarding **{query}**.
    
    ### Key Findings
    {analysis_data}
    
    ### Conclusion
    The search results indicate a significant amount of information is available. Further deep-dive research is recommended for specific sub-topics.
    
    *Generated by AI Writer Agent*
    """
    return report

# --- MAIN APP LOGIC ---

st.title("� Multi-Agent Research System")
st.markdown("### Autonomous Research Workflow Simulation")

# Layout: Graph on top, Logs/Output below
graph_container = st.empty()
log_container = st.container()

# Initial State Graph
graph_container.markdown(f"```mermaid\n{render_graph('User')}\n```", unsafe_allow_html=True)

# User Input
query = st.text_input("Enter research topic:", placeholder="e.g., The future of quantum computing")

if st.button("Start Research", type="primary"):
    if not query:
        st.warning("Please enter a query first.")
    else:
        try:
            # --- STEP 1: ROUTER ---
            graph_container.markdown(f"```mermaid\n{render_graph('Router')}\n```", unsafe_allow_html=True)
            with log_container:
                st.info(f"🔄 **Router:** Received query '{query}'. Routing to Search Agent...")
            time.sleep(1) # Visual pause

            # --- STEP 2: SEARCH AGENT ---
            graph_container.markdown(f"```mermaid\n{render_graph('Searcher')}\n```", unsafe_allow_html=True)
            with log_container:
                with st.spinner("🔍 **Search Agent:** Browsing the web..."):
                    search_results = run_google_search(query)
                    
                    # Display raw results in expander
                    with st.expander("View Raw Search Results"):
                        if search_results:
                            for item in search_results[:5]:
                                st.markdown(f"- [{item['title']}]({item['link']})")
                        else:
                            st.write("No results found.")
            
            if not search_results:
                st.error("Search Agent found no data. Stopping process.")
            else:
                # --- STEP 3: ANALYST AGENT ---
                graph_container.markdown(f"```mermaid\n{render_graph('Analyst')}\n```", unsafe_allow_html=True)
                with log_container:
                    with st.spinner("🧠 **Analyst Agent:** Analyzing patterns and extracting insights..."):
                        analysis_output = run_analyst_agent(search_results)
                        st.success("Analyst Agent finished processing.")

                # --- STEP 4: WRITER AGENT ---
                graph_container.markdown(f"```mermaid\n{render_graph('Writer')}\n```", unsafe_allow_html=True)
                with log_container:
                    with st.spinner("✍️ **Writer Agent:** Drafting final report..."):
                        final_report = run_writer_agent(analysis_output, query)
                
                # --- FINAL OUTPUT ---
                graph_container.markdown(f"```mermaid\n{render_graph('Final')}\n```", unsafe_allow_html=True)
                
                st.divider()
                st.markdown(final_report)
                st.success("✅ Research Complete")

        except Exception as e:
            st.error(f"🚨 **System Error:** An error occurred during execution.")
            st.error(f"Error Details: {str(e)}")
            st.warning("Please check your API Keys (YOUR_API_KEY and YOUR_CSE_ID) in the code.")